# Generated by Django 5.0.6 on 2025-11-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_dual_path_models"),
        ("core", "0012_userprofile"),
    ]

    operations = []
