# Generated by Django 5.0.6 on 2025-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_merge_0012_add_dual_path_models_0012_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("security", "Security"),
                            ("import", "Import"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "System Alert",
                "verbose_name_plural": "System Alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["alert_type", "-created_at"],
                name="core_system_alert_t_a841ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="systemalert",
            index=models.Index(
                fields=["resolved_at"], name="core_system_resolve_51d0f2_idx"
            ),
        ),
    ]
