# Generated by Django 5.0.6 on 2025-12-01 04:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_merge_20251130_2223"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="tsv_body",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="fine",
            name="tsv_body",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="office",
            name="tsv_body",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="procedure",
            name="tsv_body",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="advisory",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tsv_body"], name="advisory_tsv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fine",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tsv_body"], name="fine_tsv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="office",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tsv_body"], name="office_tsv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedure",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tsv_body"], name="procedure_tsv_idx"
            ),
        ),
    ]
