# Generated by Django 5.0.6 on 2025-11-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_legaldocument_legalsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="doc_type",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="legaldocument",
            name="issued_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="legalsection",
            name="section_code",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="legalsection",
            name="section_title",
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(fields=["code"], name="legaldoc_code_idx"),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["doc_type", "issued_date"], name="legaldoc_type_issued_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(fields=["agency"], name="legaldoc_agency_idx"),
        ),
    ]
