# Generated by Django 5.0.6 on 2025-11-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_legaldocument_content_checksum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mlmetrics",
            options={
                "ordering": ["-date"],
                "verbose_name": "ML Metrics",
                "verbose_name_plural": "ML Metrics",
            },
        ),
        migrations.RenameIndex(
            model_name="conversationmessage",
            new_name="core_conver_session_3904e6_idx",
            old_name="core_conver_session_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmessage",
            new_name="core_conver_session_bcaf8e_idx",
            old_name="core_conver_session_role_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationsession",
            new_name="core_conver_session_c1cf4c_idx",
            old_name="core_conver_session_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationsession",
            new_name="core_conver_user_id_30a132_idx",
            old_name="core_conver_user_id_updated_idx",
        ),
        migrations.RenameIndex(
            model_name="legaldocument",
            new_name="core_legald_doc_typ_0c6c2d_idx",
            old_name="core_legaldo_doc_typ_01ee44_idx",
        ),
        migrations.RenameIndex(
            model_name="legaldocument",
            new_name="core_legald_issued__ff64f1_idx",
            old_name="core_legaldo_issued__df806a_idx",
        ),
        migrations.RenameIndex(
            model_name="legaldocumentimage",
            new_name="core_legald_documen_dc7626_idx",
            old_name="core_legald_documen_b2f145_idx",
        ),
        migrations.RenameIndex(
            model_name="legaldocumentimage",
            new_name="core_legald_checksu_20f116_idx",
            old_name="core_legald_checksum_90ccce_idx",
        ),
        migrations.RenameIndex(
            model_name="legalsection",
            new_name="core_legals_documen_31c2b1_idx",
            old_name="core_legalse_documen_1cb98e_idx",
        ),
        migrations.RenameIndex(
            model_name="legalsection",
            new_name="core_legals_level_607853_idx",
            old_name="core_legalse_level_e3a6a8_idx",
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
