# Generated by Django 5.0.6 on 2025-11-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_dual_path_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversationmessage",
            new_name="core_conver_session_3904e6_idx",
            old_name="core_conver_session_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmessage",
            new_name="core_conver_session_bcaf8e_idx",
            old_name="core_conver_session_role_timestamp_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationsession",
            new_name="core_conver_session_c1cf4c_idx",
            old_name="core_conver_session_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationsession",
            new_name="core_conver_user_id_30a132_idx",
            old_name="core_conver_user_id_updated_idx",
        ),
        migrations.RenameIndex(
            model_name="goldenquery",
            new_name="core_golden_query_n_c7aff5_idx",
            old_name="core_golden_query_normalized_intent_idx",
        ),
        migrations.RenameIndex(
            model_name="goldenquery",
            new_name="core_golden_is_acti_8c89fa_idx",
            old_name="core_golden_query_active_intent_idx",
        ),
        migrations.RenameIndex(
            model_name="goldenquery",
            new_name="core_golden_usage_c_4ed9db_idx",
            old_name="core_golden_query_usage_count_idx",
        ),
        migrations.RenameIndex(
            model_name="legaldocument",
            new_name="core_legald_doc_typ_0c6c2d_idx",
            old_name="core_legaldo_doc_typ_01ee44_idx",
        ),
        migrations.RenameIndex(
            model_name="legaldocument",
            new_name="core_legald_issued__ff64f1_idx",
            old_name="core_legaldo_issued__df806a_idx",
        ),
        migrations.RenameIndex(
            model_name="legaldocumentimage",
            new_name="core_legald_documen_dc7626_idx",
            old_name="core_legald_documen_b2f145_idx",
        ),
        migrations.RenameIndex(
            model_name="legaldocumentimage",
            new_name="core_legald_checksu_20f116_idx",
            old_name="core_legald_checksum_90ccce_idx",
        ),
        migrations.RenameIndex(
            model_name="legalsection",
            new_name="core_legals_documen_31c2b1_idx",
            old_name="core_legalse_documen_1cb98e_idx",
        ),
        migrations.RenameIndex(
            model_name="legalsection",
            new_name="core_legals_level_607853_idx",
            old_name="core_legalse_level_e3a6a8_idx",
        ),
        migrations.RenameIndex(
            model_name="queryroutinglog",
            new_name="core_queryr_route_34ff4a_idx",
            old_name="core_query_routing_route_created_idx",
        ),
        migrations.RenameIndex(
            model_name="queryroutinglog",
            new_name="core_queryr_router__cb3d26_idx",
            old_name="core_query_routing_method_created_idx",
        ),
        migrations.RenameIndex(
            model_name="queryroutinglog",
            new_name="core_queryr_intent_97ba16_idx",
            old_name="core_query_routing_intent_created_idx",
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="conversationsession",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="goldenquery",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="queryroutinglog",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
