# Generated by Django 5.0.6 on 2025-12-01 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0013_rename_core_conver_session_timestamp_idx_core_conver_session_3904e6_idx_and_more",
        ),
        ("core", "0014_add_systemalert"),
    ]

    operations = []
